version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgresgo-db
    restart: always
    ports:
      - "7530:5432"
    environment:
      POSTGRES_DB: postgresgo
      POSTGRES_USER: pogotest
      POSTGRES_PASSWORD: go1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

volumes:
  postgres_data: